/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardServicosRouteImport } from './routes/dashboard/servicos'
import { Route as DashboardPdvRouteImport } from './routes/dashboard/pdv'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard/marketing'
import { Route as DashboardFinanceiroRouteImport } from './routes/dashboard/financeiro'
import { Route as DashboardEstoqueRouteImport } from './routes/dashboard/estoque'
import { Route as DashboardEquipeRouteImport } from './routes/dashboard/equipe'
import { Route as DashboardConfigRouteImport } from './routes/dashboard/config'
import { Route as DashboardClientesRouteImport } from './routes/dashboard/clientes'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard/agenda'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicosRoute = DashboardServicosRouteImport.update({
  id: '/dashboard/servicos',
  path: '/dashboard/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPdvRoute = DashboardPdvRouteImport.update({
  id: '/dashboard/pdv',
  path: '/dashboard/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/dashboard/marketing',
  path: '/dashboard/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFinanceiroRoute = DashboardFinanceiroRouteImport.update({
  id: '/dashboard/financeiro',
  path: '/dashboard/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEstoqueRoute = DashboardEstoqueRouteImport.update({
  id: '/dashboard/estoque',
  path: '/dashboard/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEquipeRoute = DashboardEquipeRouteImport.update({
  id: '/dashboard/equipe',
  path: '/dashboard/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConfigRoute = DashboardConfigRouteImport.update({
  id: '/dashboard/config',
  path: '/dashboard/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/dashboard/clientes',
  path: '/dashboard/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/dashboard/agenda',
  path: '/dashboard/agenda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/equipe': typeof DashboardEquipeRoute
  '/dashboard/estoque': typeof DashboardEstoqueRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/pdv': typeof DashboardPdvRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/equipe': typeof DashboardEquipeRoute
  '/dashboard/estoque': typeof DashboardEstoqueRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/pdv': typeof DashboardPdvRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/equipe': typeof DashboardEquipeRoute
  '/dashboard/estoque': typeof DashboardEstoqueRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/pdv': typeof DashboardPdvRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendar'
    | '/login'
    | '/pricing'
    | '/dashboard/agenda'
    | '/dashboard/clientes'
    | '/dashboard/config'
    | '/dashboard/equipe'
    | '/dashboard/estoque'
    | '/dashboard/financeiro'
    | '/dashboard/marketing'
    | '/dashboard/pdv'
    | '/dashboard/servicos'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agendar'
    | '/login'
    | '/pricing'
    | '/dashboard/agenda'
    | '/dashboard/clientes'
    | '/dashboard/config'
    | '/dashboard/equipe'
    | '/dashboard/estoque'
    | '/dashboard/financeiro'
    | '/dashboard/marketing'
    | '/dashboard/pdv'
    | '/dashboard/servicos'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendar'
    | '/login'
    | '/pricing'
    | '/dashboard/agenda'
    | '/dashboard/clientes'
    | '/dashboard/config'
    | '/dashboard/equipe'
    | '/dashboard/estoque'
    | '/dashboard/financeiro'
    | '/dashboard/marketing'
    | '/dashboard/pdv'
    | '/dashboard/servicos'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendarRoute: typeof AgendarRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardConfigRoute: typeof DashboardConfigRoute
  DashboardEquipeRoute: typeof DashboardEquipeRoute
  DashboardEstoqueRoute: typeof DashboardEstoqueRoute
  DashboardFinanceiroRoute: typeof DashboardFinanceiroRoute
  DashboardMarketingRoute: typeof DashboardMarketingRoute
  DashboardPdvRoute: typeof DashboardPdvRoute
  DashboardServicosRoute: typeof DashboardServicosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/servicos': {
      id: '/dashboard/servicos'
      path: '/dashboard/servicos'
      fullPath: '/dashboard/servicos'
      preLoaderRoute: typeof DashboardServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pdv': {
      id: '/dashboard/pdv'
      path: '/dashboard/pdv'
      fullPath: '/dashboard/pdv'
      preLoaderRoute: typeof DashboardPdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/dashboard/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/financeiro': {
      id: '/dashboard/financeiro'
      path: '/dashboard/financeiro'
      fullPath: '/dashboard/financeiro'
      preLoaderRoute: typeof DashboardFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/estoque': {
      id: '/dashboard/estoque'
      path: '/dashboard/estoque'
      fullPath: '/dashboard/estoque'
      preLoaderRoute: typeof DashboardEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/equipe': {
      id: '/dashboard/equipe'
      path: '/dashboard/equipe'
      fullPath: '/dashboard/equipe'
      preLoaderRoute: typeof DashboardEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/config': {
      id: '/dashboard/config'
      path: '/dashboard/config'
      fullPath: '/dashboard/config'
      preLoaderRoute: typeof DashboardConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/dashboard/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/dashboard/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendarRoute: AgendarRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardConfigRoute: DashboardConfigRoute,
  DashboardEquipeRoute: DashboardEquipeRoute,
  DashboardEstoqueRoute: DashboardEstoqueRoute,
  DashboardFinanceiroRoute: DashboardFinanceiroRoute,
  DashboardMarketingRoute: DashboardMarketingRoute,
  DashboardPdvRoute: DashboardPdvRoute,
  DashboardServicosRoute: DashboardServicosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
